<a href="https://colab.research.google.com/github/ManuJLV/PracticasIA/blob/main/Copia_de_Taller_asociaci%C3%B3n_Manuel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Actualizar la libería mlxtend
!pip install mlxtend --upgrade

Requirement already satisfied: mlxtend in /usr/local/lib/python3.10/dist-packages (0.23.3)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.5.2)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (3.8.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.54.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (24.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24.2->mlxtend) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24.2->mlxtend) (2024.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [ ]:
#Importamos las librerias a usar
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io
from google.colab import files
from mlxtend.frequent_patterns import association_rules
from mlxtend.frequent_patterns import fpgrowth

In [ ]:
uploaded = files.upload()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Saving transacciones.csv to transacciones.csv

In [ ]:
# Decode the byte stream to a string
csv_data = uploaded['transacciones.csv'].decode('utf-8')  # Assuming UTF-8 encoding
# Create a StringIO object from the decoded string
csv_buffer = io.StringIO(csv_data)
# Read the CSV data using pd.read_csv
df = pd.read_csv(csv_buffer)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
df

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,transaccion,esparragos,frijoles,brocoli,maiz,pimientosverdes,calabazas,tomates
0,1,0,0,1,1,1,0,0
1,2,1,0,0,1,0,1,0
2,3,0,1,0,1,0,1,1
3,4,0,1,0,1,1,0,1
4,5,1,1,1,0,0,0,0
5,6,1,1,0,0,0,1,1
6,7,0,0,0,1,0,0,1
7,8,0,0,1,0,1,0,1
8,9,1,1,0,0,0,1,0
9,10,0,1,0,1,0,0,0
10,11,0,1,1,0,1,1,0
11,12,1,1,0,0,0,1,0
12,13,1,1,0,1,0,1,0
13,14,0,1,1,1,1,0,1

In [ ]:
df = df.drop('transaccion', axis=1)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#Transformar todos los datos a datos binomiales
df = df.applymap(lambda x: True if x > 0 else False)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
<ipython-input-7-29784642e947>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: True if x > 0 else False)

In [ ]:
df

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    esparragos  frijoles  brocoli   maiz  pimientosverdes  calabazas  tomates
0        False     False     True   True             True      False    False
1         True     False    False   True            False       True    False
2        False      True    False   True            False       True     True
3        False      True    False   True             True      False     True
4         True      True     True  False            False      False    False
5         True      True    False  False            False       True     True
6        False     False    False   True            False      False     True
7        False     False     True  False             True      False     True
8         True      True    False  False            False       True    False
9        False      True    False   True            False      False    False
10       False      True     True  False             True       True    False
11        True      True    False  False            False       True    False
12        True      True    False   True            False       True    False
13       False      True     True   True             True      False     True

In [ ]:
#Ejecutar el algoritmo FP-Growth con sun soporte mínimo del 15%
frequent_itemsets = fpgrowth(df, min_support=0.15, use_colnames=True)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#Imprima los itemset frecuentes
frequent_itemsets

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

     support                           itemsets
0   0.571429                             (maiz)
1   0.357143                  (pimientosverdes)
2   0.357143                          (brocoli)
3   0.500000                        (calabazas)
4   0.428571                       (esparragos)
5   0.714286                         (frijoles)
6   0.428571                          (tomates)
7   0.357143                   (frijoles, maiz)
8   0.214286            (pimientosverdes, maiz)
9   0.214286         (pimientosverdes, tomates)
10  0.214286        (frijoles, pimientosverdes)
11  0.285714         (brocoli, pimientosverdes)
12  0.214286                (frijoles, brocoli)
13  0.214286                  (calabazas, maiz)
14  0.428571              (frijoles, calabazas)
15  0.357143            (calabazas, esparragos)
16  0.357143             (frijoles, esparragos)
17  0.285714  (frijoles, calabazas, esparragos)
18  0.285714                    (tomates, maiz)
19  0.285714                (frijoles, tomates)
20  0.214286          (frijoles, tomates, maiz)

In [ ]:
#Genere las reglas de asociación. Tenga en cuenta que se manejará una confianza del 70%
num_itemsets = len(frequent_itemsets)
reglas = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7, num_itemsets=len(frequent_itemsets), return_metrics=['support', 'confidence'])

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#Imprima las reglas generadas con su respectivo soporte y confianza
reglas

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

               antecedents        consequents   support  confidence
0                (brocoli)  (pimientosverdes)  0.285714    0.800000
1        (pimientosverdes)          (brocoli)  0.285714    0.800000
2              (calabazas)         (frijoles)  0.428571    0.857143
3              (calabazas)       (esparragos)  0.357143    0.714286
4             (esparragos)        (calabazas)  0.357143    0.833333
5             (esparragos)         (frijoles)  0.357143    0.833333
6   (frijoles, esparragos)        (calabazas)  0.285714    0.800000
7  (calabazas, esparragos)         (frijoles)  0.285714    0.800000
8      (frijoles, tomates)             (maiz)  0.214286    0.750000
9          (maiz, tomates)         (frijoles)  0.214286    0.750000